audit_header: false
title: Fort Collins' Best Real Estate Training
description: Rob Kittle, a top Real Estate Agent in Fort Collins, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  # - title: Events
  #   url: #
  # - title: Free Strategy Call
    # url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Rob Kittle
  title:
  license_number:
  about_markdown: |
    Rob Kittle started Kittle Real Estate in 1999 with the goal in mind to provide his clients with superior service in the Real Estate industry. Kittle Real Estate is comprised of 18 professionals that allow them to leverage their business and most importantly increase service and efficiency to their clients. The benefit to their clients is that they receive aggressive sales attention from an entire staff of professionals with one goal in mind - a successful transaction! Kittle Real Estate sold over 300 homes last year, that’s 43 times more than the average agent. Kittle Real Estate has provided Excellent Service for over 17 years and have helped over 3000 families buy or sell their home!
  market: Fort Collins
  brand: Kittle Real Estate
  brokerage:
  address: 300 S. Howes Street<br>Fort Collins, CO 80521
  phone: 970-690-4920
  phone_type:
  phone2:
  phone2_type:
  email: Rob@KittleTeam.com
  url: http://RobKittle.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/kittleteam
  linkedin_url: http://www.linkedin.com/in/thekittleteam
  gplus_url: https://plus.google.com/112882411348974197435/posts
  youtube_url: https://www.youtube.com/user/robkittle
  twitter_url: https://twitter.com/TheKittleTeam
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#af102c'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
